
services:
  - type: web
    name: amazon-flex-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        value: sqlite:////data/app.db
    disk:
      name: app-data
      mountPath: /data
      sizeGB: 1
